[package]
name = "secure_password_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
# Encryption and cryptography
ring = "0.17"
aes-gcm = "0.10"
argon2 = "0.5"
rand = "0.8"

# Data serialization and storage
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# User interface and input
rpassword = "7.3"
clap = { version = "4.4", features = ["derive"] }
colored = "2.1"

# Utilities
zeroize = { version = "1.7", features = ["zeroize_derive"] }
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.6", features = ["v4", "serde"] }

# Error handling
thiserror = "1.0"
anyhow = "1.0"
